import { ThemeProvider } from "@/providers/ThemeProvider";
import { useContext } from "react";
import { Nunito } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// const nunito = Nunito({
//   subsets: ["latin"],
//   display: "swap",
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
